/**
 * alchemy.run.ts, declarative deploy for the dynamic-workflow recipe.
 *
 * Deploys TWO Workers in one lifecycle (same shape as recipes/mcp-client):
 *
 *   1. flue-rx-dynwf-run, the durable backend. Raw Worker built from
 *      ./runner.ts. Exports the `TaskQueue` Durable Object class and
 *      the `TaskRunnerWorkflow` Workflow class, and a default fetch
 *      handler for the agent to call via service binding.
 *
 *   2. flue-rx-dynwf-cli, the Flue agent. Built by `flue build`. Owns
 *      its own `DynamicWorkflow` DO (auto-generated by Flue for session
 *      memory, even though this snippet doesn't lean on it) and a
 *      service binding to the runner Worker.
 *
 * Why two Workers?  Flue's build emits a single auto-generated
 * `_entry.ts` and does not yet support injecting extra exported classes
 * (Workflow / additional DOs) into that file. Splitting into two scripts
 * lets the runner own the Workflow class and the DO that backs the
 * task queue, while the Flue agent stays a pure Flue agent.
 *
 * The Flue agent calls the runner over a service binding (RUNNER) so
 * neither side needs Cloudflare API credentials to drive the workflow.
 */

import alchemy from 'alchemy';
import { DurableObjectNamespace, Worker, Workflow } from 'alchemy/cloudflare';

const STAGE = process.env.STAGE ?? 'local';
const SHA = process.env.GITHUB_SHA?.slice(0, 7) ?? 'local';

const app = await alchemy('flue-rx-dynamic-workflow', { stage: STAGE });

// 1. Runner Worker — hosts the DO + Workflow + control-plane fetch.
//    The DO binding name (TASK_QUEUE) must match what runner.ts uses;
//    same for the Workflow binding (TASK_RUNNER) and the class names.
const runner = await Worker(`flue-rx-dynwf-run-${SHA}`, {
  entrypoint: './runner.ts',
  compatibilityDate: '2026-04-01',
  compatibility: 'node',
  bindings: {
    TASK_QUEUE: DurableObjectNamespace('TaskQueue', {
      className: 'TaskQueue',
      sqlite: true,
    }),
    TASK_RUNNER: Workflow('TaskRunnerWorkflow', {
      className: 'TaskRunnerWorkflow',
      workflowName: `flue-rx-dynwf-runner-${SHA}`,
    }),
  },
});

// 2. Flue agent Worker — talks to the runner via a service binding.
//    `flue build` emits the DynamicWorkflow DO class (one per agent file).
const client = await Worker(`flue-rx-dynwf-cli-${SHA}`, {
  entrypoint: '.build/dist/_entry.ts',
  compatibilityDate: '2026-04-01',
  compatibility: 'node',
  bindings: {
    DynamicWorkflow: DurableObjectNamespace('DynamicWorkflow', {
      className: 'DynamicWorkflow',
      sqlite: true,
    }),
    // Passing the runner Worker value here creates a service binding.
    // The agent calls it as `env.RUNNER.fetch(...)`.
    RUNNER: runner,
    RUNNER_URL: `${runner.url}`,
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID ?? '',
    CLOUDFLARE_API_KEY: process.env.CLOUDFLARE_API_TOKEN ?? '',
  },
});

// Print runner URL for humans, then client URL last so run-e2e.sh's
// `tail -1` grep grabs the client (the thing the probe hits).
console.log(`RUNNER: ${runner.url}`);
console.log(`CLIENT: ${client.url}`);
console.log(client.url);

await app.finalize();
