/**
 * alchemy.run.ts, declarative deploy for the chat-thinking recipe.
 *
 * Two Durable Object namespaces:
 *   - `ChatThinking`, auto-generated by `flue build` (one DO per agent,
 *     for Flue's own session/routing plumbing).
 *   - `Thinker`, the `@cloudflare/think` subclass exported from
 *     `agents/chat-thinking.ts`. Holds the persistent chat history per
 *     chatId (SQLite-backed, geo-pinned, restart-safe).
 *
 * Plus the `AI` binding for Workers AI (the kimi-k2.6 completion
 * model Think calls via `workers-ai-provider`).
 *
 * No wrangler. `alchemy deploy` owns the resource graph;
 * `alchemy destroy` tears it down.
 */

import alchemy from 'alchemy';
import { Ai, DurableObjectNamespace, Worker } from 'alchemy/cloudflare';

const STAGE = process.env.STAGE ?? 'local';

const app = await alchemy('flue-rx-chat-thinking', { stage: STAGE });

const worker = await Worker(`flue-rx-ct-${STAGE}`, {
  entrypoint: '.build/dist/_entry.ts',
  compatibilityDate: '2026-04-01',
  compatibility: 'node',
  bindings: {
    AI: Ai(),
    ChatThinking: DurableObjectNamespace('ChatThinking', {
      className: 'ChatThinking',
      sqlite: true,
    }),
    Thinker: DurableObjectNamespace('Thinker', {
      className: 'Thinker',
      sqlite: true,
    }),
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID ?? '',
    CLOUDFLARE_API_KEY: process.env.CLOUDFLARE_API_TOKEN ?? '',
  },
});

console.log(worker.url);

await app.finalize();
